# Generated by Django 2.1.7 on 2019-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_remove_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, null=True, on_delete='CASCADE', to='lists.List'),
        ),
    ]
